### PR TITLE
Added a similarity computation on Rapidminer

### PR DESCRIPTION
**Pull request by GizKockesen**
The .rmp file is the process that has the similarity computation so you
just have to import it onto Rapidminer. It should come with the
properties already set because I exported the process. If not, then I
can add the properties file as well. I included the csv file that I
tested the program with and the resulting excel file with the similarity
scores in the folder.

What I did to initially test the program was to compute the similarity
of the data in the csv file using cosine similarity. What the process
does is the following:
- Read CSV: loads and reads the csv file containing the data. Its output
  is connected to the exa (means example set) input of the next function.
- Process Document: This is used for all kinds of text analysis. If you
  double click it, you will see that for now it only transforms the data
  case to lowercase. In the parameters of Process Document, you will see
  that the "create vector space" is checked and is created using TF-IDF.
  The output of Process Document is an example set going to the exa input
  of the next function.
- Data to Similarity: This is where the similarity of each data in the
  file is computed using cosine similarity. The output "sim" outputs the
  similarity score and "exa" is the example set. In order to export the
  result with the similarity scores, both of those outputs must go to the
  corresponding inputs of the next function.
- Similarity to Data: This is needed to convert the similarity scores to
  data so that it can be written on a file. Otherwise, you can only view
  the results inside Rapidminer. The output is an example set going to the
  next function.
- Write Excel: This writes the example set that it received from the
  previous function onto an excel file. The output goes from the "thr"
  output to "res" (result).
- Press the play button at the top to start the process.

### CODE REVIEW

**Comment by millenniumproof** [comment]
How come similarity scores in the results are either 0 or 1? Shouldn't they be in between? When I try running the process everything gets 1 similarity :S

**Comment by GizKockesen** [comment]
I realized that I forgot to add one more process (tokenizing), I will add
that to github tomorrow. That solves that problem. Sorry!!

**Comment by GizKockesen** [comment]
I've been trying to add the new file to github but it doesn't work for some reason. I'm gonna try again later, if it doesn't work again maybe I can e-mail it to all of you.

**Comment by GizKockesen** [comment]
It works now :) The calculation is now not only 0 or 1 but a value between that range depending on the similarity.

**Comment by millenniumproof** [comment]
Great. Can you run the test data through RapidMiner. I put it in the documents folder on Github.

**Comment by GizKockesen** [comment]
I did and it works but that csv file wraps texts in some cells and when it
does that, rapidminer can't read those cells so it ignores them. I'm gonna
try deselecting the wrap text option on excel.

**Comment by GizKockesen** [comment]
Yeah it's strange, it can't read those cells and whenever I deselect "wrap
text" and save, it selects that option again after the save.

**Comment by GizKockesen** [comment]
When I do the similarity check with the cells that it does recognize, it
works fine though. It gives the same apps higher similarity scores. Should
I put the result on the documents folder on github? I can also put up the
spreadsheet of the cells that rapidminer recognizes for you compare the
results.

**Comment by GizKockesen** [comment]
I copied the text from github onto a new csv file and now rapidminer reads
all cells. Somehow something reformats the cells. I'll put up the
similarity results on github now.

**Comment by millenniumproof** [comment]
Great! Annoying that you had problems with the formatting. I already used up all my units for the day for dandelion :S Wonder which of the two gets better results.

**Comment by GizKockesen** [comment]
Yeah it's strange. I think I committed to master while adding the
similarity results but I think I didn't break anything since I just created
a new file :S :P

**Pull request closed without merging**
