### PR TITLE
Fixed typos and rephrased some parts

### PR DESCRIPTION
**Pull request by millenniumproof**
I wonder if the voting is also a type of human computation.

### CODE REVIEW

**Comment by PetervB** [comment]
Good question, one could argue for it but I don't know if it isn't pushing the idea too far?

**Comment by HDking** [comment]
It is I think.. computers would not be able to do this. But, on the other hand the main reason that we let people rate the ideas is not because it is too hard for computers, but we just want to know user preference..

**Comment by GizKockesen** [comment]
I think we have enough for human computation so it might not be confusing
to also say that voting is human computation. I think, like Hao mentioned,
the reason for getting votes is different than the reasoning behind human
computation tasks.

**Comment by GizKockesen** [comment]
*I meant it might be confusing

**Comment by alex9311** [comment]
should we merge this in?

**Comment by HDking** [comment]
Go ahead! I'm out btw!

**Pull request merged**
