### PR TITLE
added use case UMLs

### PR DESCRIPTION
**Pull request by HDking**

### CODE REVIEW

**Comment by alex9311** [comment]
This looks good. It really is subjective but I would change some of the arrows.

Rather than having an arrow go from the "idea submitter" to "sees status of submitted idea" I would have the arrow go from "submit idea" to "sees status of submitted idea". This might show more of a flow between those actions. That pattern would follow in the other processes the user goes through in the system.

I think it would make it more clear to have both ingoing and outgoing arrows of the "sanitation check" box. So for the first santitation check of the user idea, there would be one arrow that sends the "submitted idea" to the sanitation check and another arrow that sends it back to a "checked idea state". This might be overcomplicating things, not sure

**Comment by PetervB** [comment]
I think it would be good to make the steps more clear. Depending on which step/stage we are the submitter and voter can take different actions. Maybe make it more clear when which action is applicable?

Submit idea
Sanitation check
Accept/reject idea
Voting

**Comment by HDking** [comment]
Ok! I'm going to implement these ideas and change it into multiple diagrams which show a differen status of the idea in the flow..

**Comment by PetervB** [comment]
After submission -> Idea accepted

Might be better, for the rest it looks a lot better I think :)

**Comment by millenniumproof** [comment]
In the diagram it looks as though any user can see the ranking of ideas any time. Only the user who submitted the idea can see the ranking of only the ideas he submitted.

**Comment by HDking** [comment]
what about the other users? So ideas are never accessible for others?

**Comment by millenniumproof** [comment]
They can access them once to vote, but they won't see the ranking or the number of votes an idea has.

**Comment by HDking** [comment]
Then also see the progress on the ideas that they have voted for? I recall that this was the incentive as well

**Comment by millenniumproof** [comment]
Only the user who submitted the idea can see the ranking of his own idea. If anyone can see the ranking of all the ideas than business can easily steal ideas if they see it has a high ranking. We keep that data hidden to the average user because of the value it has in seeing what resonates with people.

**Comment by HDking** [comment]
So then the change will be: 
- Remove "See ranking ideas" 
- Change title third section to idea accepted
  for the rest the same? 

I think it would be nice to receive an update if the idea is getting to a different stage for example and I think it works if the idea can be shared immediately

**Comment by HDking** [comment]
now I have to leave EWI ;)

**Comment by millenniumproof** [comment]
We could make it possible for any user to browse the ideas so that they can still see and share them even after voting. We just don't want to show them the ranking. I guess we could send a notice to all the people who voted for the idea when an idea is to be developed further.

**Comment by HDking** [comment]
Yes, that is showed now in the graph (kind off), but needs text addition i guess?

**Comment by millenniumproof** [comment]
Alrighty then :)

**Comment by PetervB** [comment]
Looks good I think

**Pull request merged**
