### PR TITLE
goal tree time!

### PR DESCRIPTION
**Pull request by HDking**

### CODE REVIEW

**Comment by alex9311** [comment]
:thumbsup: looks great to me!

**Comment by millenniumproof** [comment]
What do you mean by 'Flawless gather ideas from crowd'? Why flawless? And does 'easy rankable' refer to the voting? I don't think we should use the words ranking and voting interchangeably. The user votes, the system ranks.

**Comment by PetervB** [comment]
The goal is to get a ranking, how to achieve a ranking is by voting.

**Comment by millenniumproof** [comment]
I got from the text that it refers to the goal of 'easy voting'. Meaning that we intend to make the voting process easy for the user. 'Easy rankable' doesn't make much sense as a goal.

**Comment by PetervB** [comment]
Ah, well we can make it easy voting if that makes more sense. Hao could you change that?

**Comment by HDking** [comment]
Yes, more? lets do it all at the same time

**Comment by PetervB** [comment]
It looks good, same as we discussed :)

**Comment by millenniumproof** [comment]
Maybe from the top node also have a node saying "Gather data for Market Research (out of scope)". Just to show that we've also thought about other Information Retrieval techniques.

**Comment by millenniumproof** [comment]
Other than that I think it looks good :)

**Comment by HDking** [comment]
I think that that actually falls under the app, as you will need to get data from somewhere ;)

**Comment by millenniumproof** [comment]
No, I mean actually doing more with the data we're getting. Processing it into a form that's more useful for people interested in the mobile market. Our app only ranks on popularity, while there's a lot more you could be able to tell from the data we gather. Like I said (out of scope), but good to show to the professor that we thought about it.

**Comment by HDking** [comment]
I;ve posted another version, not sure if it grasps what you are saying..

**Comment by millenniumproof** [comment]
Maybe say "Process Data for in-depth Market Research (out of scope)". I think 'process' probably better describes it.

**Comment by HDking** [comment]
final version here

**Comment by millenniumproof** [comment]
Looks great!

**Pull request merged**
