### PR TITLE
Integrated goal tree (needs text)

### PR DESCRIPTION
**Pull request by PetervB**

### CODE REVIEW

**Comment by PetervB** [comment]
I did not add text yet for the objectives part, who has an idea what to put there?

**Comment by HDking** [comment]
how could I commit on the same branch? This is what I do not understand.

**Comment by PetervB** [comment]
go to view and click edit

**Comment by alex9311** [comment]
since this wasnt merged before I did my work, there are now conflicts. I copy pasted the content into a new branch and committed directly to master.

Please remember to try not to leave unmerged branches before going to sleep!

**Pull request closed without merging**
